version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    command: "npm start"
    user: "node"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app/code
    expose:
      - "8080"
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sJlaNwiaB
